spring:
  mail:
    host: smtp-relay.brevo.com
    username: 9edc3f001@smtp-brevo.com
    password:  ${PASSWORD_MAIL}

front-base-url: https://socialnetworkisep.hangar.garageisep.com
file-directory: /app/upload/
